swagger: "2.0"
info:
  version: 1.0.0
  title: myapp
  description: Heroku Connnect API test
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

components:
  schemas:
    User: 
      type: object
      properties:
        username:
          type: string
        password:
          type: string

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
  User: 
    type: object
    title: example
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string

paths:
  /get_user:
    post:
      description: Login validation
      parameters:
        - name: login
          in: body
          description: login validation
          required: true
          schema: 
            $ref: "#/definitions/User"
      responses:
        200:
          description: Status OK
        401:
          description: Error
  /examples:
    get:
      tags:
        - Users
      description: Fetch all users
      responses:
        200:
          description: Returns all users
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification